---
apiVersion: v1
kind: Namespace
metadata: 
  name: myns
  labels:
    owner: zj

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: moneytree-deployment
  labels:
    app: moneytree
    developer: zjbro
  namespace: myns

spec:
  replicas: 2
  selector:
    matchLabels:
      name: moneytree-po
  template:
    metadata:
      name: moneytree-po
      labels:
        name: moneytree-po
    spec:
      containers:
      - name: moneytree-container
        image: zjbro/moneytree:1.5.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: moneytree-svc-lb
  namespace: myns
spec:
  type: LoadBalancer
  selector:
    name: moneytree-po
  ports:
  - name: p80
    port: 80
    targetPort: 8080